name: Update README

on:
  push:
    paths:
      - 'pom.xml'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up git credentials
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Extract version from pom.xml
        id: version
        run: |
          VERSION=$(grep -oPm1 "(?<=<version>)[^<]+" pom.xml | head -1)
          MINECRAFT_VERSION=${VERSION%%-*}

          if [[ -z "$VERSION" ]]; then
            echo "Couldn't extract version from pom.xml!"
            exit 1
          fi

          echo "Version (from pom.xml): $VERSION"
          echo "Minecraft version: $MINECRAFT_VERSION"
          echo "::set-output name=VERSION::$VERSION"
          echo "::set-output name=MINECRAFT_VERSION::$MINECRAFT_VERSION"

      - name: Update README.md
        run: |
          sed -i "s/<!--mcversion-->.*<!--mcversion-->/<!--mcversion-->${{ steps.version.outputs.MINECRAFT_VERSION }}<!--mcversion-->/" README.md
          git add README.md

      - name: Update Beginners.md
        run: |
          sed -i "s/<!--mcversion-->.*<!--mcversion-->/<!--mcversion-->${{ steps.version.outputs.MINECRAFT_VERSION }}<!--mcversion-->/" guides/Beginners.md
          git add guides/Beginners.md
      
      - name: Commit and push changes
        run: |
          git commit -m "Update to Minecraft ${{ steps.version.outputs.MINECRAFT_VERSION }}" -m "[skip ci]"
          git push